require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'castleFortressGame' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "../node_modules/react-native-permissions/ios/Camera.podspec"
  
  pod 'RNAudio', :path => '../node_modules/react-native-audio'

  pod 'RNSound', :path => '../node_modules/react-native-sound'

  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  pod 'RNScreens', :path => '../node_modules/react-native-screens'

  pod 'react-native-safe-area-context', :path => '../node_modules/react-native-safe-area-context'

  pod 'RNCMaskedView', :path => '../node_modules/@react-native-community/masked-view'

  pod 'RNAudioRecord', :path => '../node_modules/react-native-audio-record'

  pod 'RNPermissions', :path => '../node_modules/react-native-permissions'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  # Firebase Configuration
  
  pod 'Firebase/Analytics'

  pod 'RNFBApp', :path => '../node_modules/@react-native-firebase/app'

  pod 'RNFBFirestore', :path => '../node_modules/@react-native-firebase/firestore'

  pod 'RNFBAuth', :path => '../node_modules/@react-native-firebase/auth'

  pod 'RNFBFunctions', :path => '../node_modules/@react-native-firebase/functions'

  target 'castleFortressGameTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'castleFortressGame-tvOS' do
  # Pods for castleFortressGame-tvOS

  target 'castleFortressGame-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
